apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days before expiration
  commonName: "*.vault.svc.cluster.local"
  dnsNames:
  - vault
  - vault-0
  - vault-1
  - vault-2
  - "*.vault-internal"
  - vault.vault
  - vault.vault.svc
  - vault.vault.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: vault-selfsigned-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - server auth

